config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks do
    member do
      get 'share'
      post 'create_shared'
    end
  end
  root 'tasks#index'

end

app/models/shared_task.rb
class SharedTask < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many :sharedTasks, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true

  def owner?(current_user)
    self.user_id.eql?(current_user.id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks, dependent: :destroy
  has_many :sharedTasks, dependent: :destroy

  validates :email, uniqueness: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :find_task, only: [:show, :edit, :update, :destroy, :share]
  before_action :get_tasks, only: [:index, :create]

  def index; end

  def show; end

  def new
    @task = Task.new
  end

  def edit; end

  def create
    @task = current_user.tasks.build(task_params)

    if @task.save
      sync_new @task, scope: @tasks
      redirect_to @task, notice: 'Task was successfully created.'
    else
      render :new, notice: 'Task was already shared with this user.'
    end
  end

  def update
    if @task.update(task_params)
      sync_update @task
      redirect_to @task, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    sync_destroy @task
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  def share; end

  def create_shared
    user = User.find_by_email(params[:create_shared][:email])
    
    if user.nil? || SharedTask.where(user_id: user_id, task_id: params[:id]).any?
      flash[:notice] = "Task was already shared with this user or User with this email doesn't exist."
      render :share
    else
      SharedTask.create(user_id: user.id, task_id: params[:id])
      redirect_to tasks_url, notice: 'Task was successfully shared.'
    end
  end

  private
    def find_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:name, :description)
    end

    def get_tasks
      user_id = current_user.id
      task_ids = SharedTask.where(user_id: user_id).map(&:task_id)
      tasks = Task.where(user_id: user_id)
      shared_tasks = Task.where(id: task_ids)
      @tasks = tasks + shared_tasks
    end

    def find_user(params)
      if User.find_by_email(params[:create_shared][:email]).id
        user_id =  User.find_by_email(params[:create_shared][:email]).id
      else
        flash[:notice] = "User with this email don't exist."
        render :share
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title TaskManager
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag Sync.adapter_javascript_url, 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-default role="navigation" 
      .container-fluid
        .navbar-header
          button.navbar-toggle.collapsed data-target="#main_navbar" data-toggle="collapse" type="button" 
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to 'Tasks', root_path,:class => 'navbar-brand'
        #main_navbar.collapse.navbar-collapse     
          ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              li
                = link_to 'Edit_profile', edit_user_registration_path
              li
                = link_to 'Logout', destroy_user_session_path, method: :delete
            - else
              li
                = link_to 'Register', new_user_registration_path
              li
                = link_to 'Login', new_user_session_path
    .container-fluid
      .raw
        .col-xs-10.col-xs-offset-1.col-sm-8.col-sm-offset-2.col-md-6.col-md-offset-3
          - flash.each do |name, msg|
            = content_tag :div, msg, :id => "flash_#{name}"
          = yield

app/views/sync/tasks/_list.html.slim
tr
  td
    = task.name
  td
    = task.description
  td
    - unless task.owner?(current_user)
      = task.user.name
  td
    = link_to 'Show', task, :class => "btn btn-info"
  td
    = link_to 'Edit', edit_task_path(task), :class => "btn btn-success"
  td
    = link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger"
  - if task.owner?(current_user)
    td
      = link_to 'Share', share_task_path(task), :class => "btn btn-primary"

app/views/tasks/_form.html.slim
= form_for(@task, :html => { :class => "form-horizontal", :role => "form" }) do |f|
  - if @task.errors.any?
    #error_explanation
      h2
        = pluralize(@task.errors.count, "error")
        prohibited this task from being saved:
      ul
        - @task.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :name, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, :class => "form-control"
  .form-group
    = f.label :description, :class => "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :description, :class => "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit :class => "btn btn-primary"

app/views/tasks/edit.html.slim
h2
  =  'Edit'
= render 'form'
.col-sm-offset-2.col-sm-10
  = link_to 'Show' ,task_path
  = ' | '
  = link_to 'Back', tasks_path

app/views/tasks/index.html.slim
h2
  = 'Listing tasks'
br/
table.table
  tr
    th
      = 'Name'
    th
      = 'Description'
    th
      = 'Shared by'
    th
    th
    th
  - @tasks.each do |task|
    = sync partial: 'list', resource: task
  = sync_new partial: 'list', resource: Task.new, scope: @tasks
br/
= link_to 'New task', new_task_path, :class=>"btn btn-warning"

app/views/tasks/new.html.slim
h2
  = 'New task'
= render 'form'
.col-sm-offset-2.col-sm-10
  = link_to 'Back', tasks_path

app/views/tasks/share.html.slim
h2
  = 'Share'
= form_for :create_shared, { url: create_shared_task_path, :html => { :class => "form-horizontal", :role => "form" } } do |f|
  .form-group
    = f.label :email, :class => "col-sm-2 control-label"
    .col-sm-8
      = f.text_field :email, :class => "form-control"
      br/
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit 'Share', :class => "btn btn-primary"
br/
.col-sm-offset-2.col-sm-10
  = link_to 'Back', tasks_path

app/views/tasks/show.html.slim
h3
  = 'Task'
table.table
  tr
    th
      = 'Name'
    th
      = 'Description'
  tr
    td
      = @task.name
    td
      = @task.description
br/
= link_to 'Edit', edit_task_path
= ' | '
= link_to 'Back', tasks_path